require 'rest-client'
require 'pry'
require 'json'
require 'PStore'
require_relative 'key'
require_relative  '../lib/get_players'
require_relative  '../lib/create_PStore'
require_relative  '../lib/CLI'
